services:
  postgres:
    image: postgres:17
    container_name: postgres17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - red_postgres_compartida

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: norio@google.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "81:80"
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin
    networks:
      - red_postgres_compartida

volumes:
  data_postgres:
  data_pgadmin:

networks:
  red_postgres_compartida:
